<<<<<<< HEAD
<<<<<<< HEAD
title: 瑾年的Blog
subtitle: ' '
description: '桃李不言,下自成蹊'
keywords: null
author: 瑾年
language: zh-CN
timezone: 
url: https://www.mckinleylu.com/
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
index_generator:
  path: ''
  per_page: 12
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 6
pagination_dir: page
include: null
exclude: null
ignore: null
theme: hexo-theme-matery

deploy:
- type: baidu_url_submitter
- type: git
  repo: 
    #github: git@github.com:McKinleyLu/mckinleylu.github.io.git
    #coding: https://e.coding.net/mckinleylu/mckinleylu.coding.me.git
    #aliyun: root@8.140.174.88:/home/git/hexoBlog  
    tengxunyun: root@101.43.163.162:/home/blog.git
    
  
server:
  port: 4000 #端口号随意，默认是4000
  compress: true
  header: true
  
sitemap:
    path: sitemap.xml
baidusitemap:
    path: baidusitemap.xml
    
baidu_url_submit:
  count: 3                      ## 比如3，代表提交最新的三个链接
  host: www.mckinleylu.com      ## 在百度站长平台中注册的域名
  token: ptvLbPJcwaZ0fLh1       ## 请注意这是您的秘钥，请不要发布在公众仓库里!
  path: baidu_urls.txt          ## 文本文档的地址，新链接会保存在此文本文档里
  
  
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date


search:
  path: search.xml
  field: post
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'
  

# hexo-admin authentification
admin:
  username: mckinleylu
  password_hash: $2a$10$ZOGpSfowfe4j3cNkBhTLYOuickGOB28ubNwCAO9KUnFIglQnJ6vFa
  secret: hdkasjiasjjsk
  deployCommand: './admin_script.sh'
  
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''
=======
title: 瑾年的Blog
subtitle: ' '
description: '桃李不言,下自成蹊'
keywords: null
author: 瑾年
language: zh-CN
timezone: 
url: https://www.mckinleylu.com/
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
index_generator:
  path: ''
  per_page: 12
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 6
pagination_dir: page
include: null
exclude: null
ignore: null
theme: hexo-theme-matery

deploy:
- type: baidu_url_submitter
- type: git
  repo: 
    #github: git@github.com:McKinleyLu/mckinleylu.github.io.git
    #coding: https://e.coding.net/mckinleylu/mckinleylu.coding.me.git
    #aliyun: root@8.140.174.88:/home/git/hexoBlog  
    tengxunyun: root@101.43.163.162:/home/blog.git
    
  
server:
  port: 4000 #端口号随意，默认是4000
  compress: true
  header: true
  
sitemap:
    path: sitemap.xml
baidusitemap:
    path: baidusitemap.xml
    
baidu_url_submit:
  count: 3                      ## 比如3，代表提交最新的三个链接
  host: www.mckinleylu.com      ## 在百度站长平台中注册的域名
  token: ptvLbPJcwaZ0fLh1       ## 请注意这是您的秘钥，请不要发布在公众仓库里!
  path: baidu_urls.txt          ## 文本文档的地址，新链接会保存在此文本文档里
  
  
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date


search:
  path: search.xml
  field: post
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'
  

# hexo-admin authentification
admin:
  username: mckinleylu
  password_hash: $2a$10$ZOGpSfowfe4j3cNkBhTLYOuickGOB28ubNwCAO9KUnFIglQnJ6vFa
  secret: hdkasjiasjjsk
  deployCommand: './admin_script.sh'
  
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''
>>>>>>> f0932680e6c46a5a85c06195d13fca9ae84cc6da
=======
title: 瑾年的Blog
subtitle: ' '
description: '桃李不言,下自成蹊'
keywords: null
author: 瑾年
language: zh-CN
timezone: 
url: https://www.mckinleylu.com/
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
index_generator:
  path: ''
  per_page: 12
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 6
pagination_dir: page
include: null
exclude: null
ignore: null
theme: hexo-theme-matery

deploy:
- type: baidu_url_submitter
- type: git
  repo: 
    #github: git@github.com:McKinleyLu/mckinleylu.github.io.git
    #coding: https://e.coding.net/mckinleylu/mckinleylu.coding.me.git
    #aliyun: root@8.140.174.88:/home/git/hexoBlog  
    tengxunyun: root@101.43.163.162:/home/blog.git
    
  
server:
  port: 4000 #端口号随意，默认是4000
  compress: true
  header: true
  
sitemap:
    path: sitemap.xml
baidusitemap:
    path: baidusitemap.xml
    
baidu_url_submit:
  count: 3                      ## 比如3，代表提交最新的三个链接
  host: www.mckinleylu.com      ## 在百度站长平台中注册的域名
  token: ptvLbPJcwaZ0fLh1       ## 请注意这是您的秘钥，请不要发布在公众仓库里!
  path: baidu_urls.txt          ## 文本文档的地址，新链接会保存在此文本文档里
  
  
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date


search:
  path: search.xml
  field: post
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'
  

# hexo-admin authentification
admin:
  username: mckinleylu
  password_hash: $2a$10$ZOGpSfowfe4j3cNkBhTLYOuickGOB28ubNwCAO9KUnFIglQnJ6vFa
  secret: hdkasjiasjjsk
  deployCommand: './admin_script.sh'
  
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''
>>>>>>> 725fcb7a857252b3986fe8e21eadbeb0e3e3ddc6
